### ISSUE TITLE
Get domain name registration credentials 

### ISSUE THREAD

**Issue by andrewsu** [biocuration/isb-website#12]
We will need domain name registration credentials for biocuration.org when we migrate the site to wpengine.  It [looks](http://whois.domaintools.com/biocuration.org) like Pascale has this info?  Assigning to Moni (assuming she knows)...

(These credentials should be put into an ISB lastpass account for security and posterity.)

**Comment by monicacecilia** [comment]
@pgaudet has these credentials. Tagging her here as well to remind us to transfer details.  Thanks in advance!

**Comment by pgaudet** [comment]
Dear Andrew, Moni, 

The domain is registered at the Biocuration society but I am indeed the contact person. Let me know how to proceed to change this. 

Thanks, Pascale

**Comment by andrewsu** [comment]
Hi Pascale,

Unless there is some prior agreement that I'm not aware of, I think the biocuration.org registration information should be transferred to ISB.  If that works, can you please email intsocbio@gmail.com with the registrar name and login credentials.  We will immediately get that imported into our ISB lastpass account and change the password.  We will also update the contact info so that the ISB Chair gets the renewal notices.  Then we should also be in shape to make the DNS change when we are ready to migrate!

Best,
-andrew

**Comment by pgaudet** [comment]
Hi Andrew,

The owner of the site *is* the ISB:
http://whois.domaintools.com/biocurator.org

My understanding is that there need to be a contact person; that's what my
name there does. Please let me know what I should do.

Thanks, Pascale

**Comment by andrewsu** [comment]
Hi Pascale,

It looks like the domain registrar (and possibly the web hosting provider?) is OVH. You may have gotten a reset password from them earlier as I was trying to confirm this. We need the login credentials for that site (which I'm presuming is also managing the DNS entries). If you use that account for other sites or domains besides biocuration.org and biocurator.org, let me know and we'll figure out a way to transfer those domains into a separate account. Let me know if I've erred in any of my guesswork, or if you need more info!

Best,
-andrew

**Comment by pgaudet** [comment]
Hi Andrew,  OVH is indeed the host of the biocurator domain.  Moni has the
ovh credentials.  I haven't seen any password reset message.

Thanks,  Pascale

Le 11 févr. 2017 5:20 PM, "Andrew Su" <notifications@github.com> a écrit :

Hi Pascale,

It looks like the domain registrar (and possibly the web hosting provider?)
is OVH. You may have gotten a reset password from them earlier as I was
trying to confirm this. We need the login credentials for that site (which
I'm presuming is also managing the DNS entries). If you use that account
for other sites or domains besides biocuration.org and biocurator.org, let
me know and we'll figure out a way to transfer those domains into a
separate account. Let me know if I've erred in any of my guesswork, or if
you need more info!

Best,
-andrew

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/biocuration/isb-website/issues/12#issuecomment-279156700>,
or mute the thread

**Comment by andrewsu** [comment]
Got it, thank you Pascale! Appreciate you bearing with me as I get oriented.  We'll do our best to get this better organized for future knowledge transfer as well...

Sending this back to @monicacecilia then! Moni, if you do have/find the ovh credentials, then please get them added to the isb lastpass account. If that lastpass account doesn't exist yet, let me know and I will set it up...

**Comment by monicacecilia** [comment]
@andrewsu you should have all credentials (see messages from 2017-02-15). Adding note here to be thorough.

**Comment by andrewsu** [comment]
confirmed!

**Comment by andrewsu** [comment]
confirmed that we can modify DNS entries through OVH control panel, and that OVH credentials added to lastpass.
