### ISSUE TITLE
BioDBcore.org URL not found

### ISSUE THREAD

**Issue by Drosophilic** [biocuration/isb-website#14]
The www.biodbcore.org URL used to redirect to a page on ISB, most likely this one:
http://biocuration.org/community/standards-biodbcore/
However it is currently returning a 'Not found' on the ISB website.

**Comment by andrewsu** [comment]
@monicacecilia is biodbcore.org an ISB asset?  I don't see it registered through the ISB account with OVH...

**Comment by monicacecilia** [comment]
ISB does not own biodbcore.org 
[This page](http://biocuration.org/community/standards-biodbcore/motivation/) discusses ways to implement BioDBCore standards via creating or claiming entries in [BioSharing](https://biosharing.org/).
@pgaudet was lead in 2011 effort that gave birth to BioDBCore, as well as populated the site with the information. Pascale, I would like for us to figure out the best way to represent BioDBCore. Where should biodbcore.org direct users? Who owns / maintains the domain, the content?

**Comment by pgaudet** [comment]
Hello,

I guess the domain name expired and I didn't notice ! We could but it
again. I let you guys decide.


Anyways it was pointing here: https://biosharing.org/databases/

Cheers,

Pascale

**Comment by Drosophilic** [comment]
Hi all,
Yes, BioSharing now maintains a registry of all databases using BioDBcore
IDs, but we don't own the bioDBcore.org domain. Anything related to
BioDBcore should point towards BioSharing. I'm happy to update the page on
ISB.

**Comment by andrewsu** [comment]
The whois record seems to suggest that it is registered until 2019 https://whois.icann.org/en/lookup?name=biodbcore.org .  There is an obfuscated email address there in case anyone wanted to try to track down the owner...

Note also that the current set up is pretty brittle.  biodbcore.org points to 205.178.189.131, which then tries to load http://biocurator.org/biodbcore.shtml in an IFRAME, which then 301 redirects to http://biocuration.org/biodbcore.shtml, which then finally returns a 404.  It is completely under our control to fix that last 404, but if anyone really cares about this, I suggest trying to fix the upstream steps as well.

**Comment by pgaudet** [comment]
I used to own the domain. I think Susanna's group did the redirect.


Pascale

Le 29 mars 2017 9:14 PM, "Andrew Su" <notifications@github.com> a écrit :

The whois record seems to suggest that it is registered until 2019
https://whois.icann.org/en/lookup?name=biodbcore.org . There is an
obfuscated email address there in case anyone wanted to try to track down
the owner...

Note also that the current set up is pretty brittle. biodbcore.org points
to 205.178.189.131, which then tries to load http://biocurator.org/
biodbcore.shtml in an IFRAME, which then 301 redirects to
http://biocuration.org/biodbcore.shtml, which then finally returns a 404.
It is completely under our control to fix that last 404, but if anyone
really cares about this, I suggest trying to fix the upstream steps as well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/biocuration/isb-website/issues/14#issuecomment-290195587>,
or mute the thread

**Comment by Drosophilic** [comment]
I've re-written the offending page so the orphaned biodbcore.org domain is not necessary.
