### ISSUE TITLE
Need a page on "Why become a biocurator?"

### ISSUE THREAD

**Issue by selewis** [biocuration/isb-website#9]
Or
"How to become a biocurator"
or
"Biocuration as a career"
or
"What does it take to become a biocurator?"

**Comment by andrewsu** [comment]
Need a volunteer to write that copy.  After that's complete, should be simple to add to website...

**Comment by monicacecilia** [comment]
I prepared and provided Text, now included in notes (presentation) from March ISB-EC meeting and available on shared drive.

**Comment by andrewsu** [comment]
@monicacecilia forgive me, I'm probably missing something obvious here, but I can't find the text you wrote.  In the March EC meeting minutes I only see a link to the google drive, but I can't find the specific text you want posted to the website.  Can you put the link to that document directly in this ticket?

**Comment by monicacecilia** [comment]
Actually, we have had one such page "Why join the ISB" since __February 9th of 2014__. It can be found under Membership / Why join the ISB?

I have updated the information there with the details I shared back at the Biocuration conference in Palo Alto. 

See https://www.biocuration.org/membership/join-isb/
